# Generated by Django 5.0.4 on 2024-05-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_super_user',
            new_name='is_superuser',
        ),
    ]
