# Generated by Django 5.0.4 on 2024-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_can_be_contacted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_be_contacted',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_data_be_shared',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.IntegerField(default=False),
        ),
    ]
