# Generated by Django 5.0.4 on 2024-05-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_customproject_contributors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={},
        ),
        migrations.RemoveField(
            model_name='customproject',
            name='contributors',
        ),
    ]
