# Generated by Django 5.0.4 on 2024-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default='default_issue', max_length=150),
        ),
    ]
