# Generated by Django 5.0.4 on 2024-05-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_issue_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_given_to_user', to='projects.contributor'),
        ),
    ]
