# Generated by Django 5.0.4 on 2024-05-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_issue_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='created_by',
            new_name='author',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('uuid', models.CharField(max_length=15000)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_comment', to='projects.contributor')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_commented', to='projects.issue')),
            ],
        ),
    ]
